contact_links:
  - name: Discussion
    about: Discuss your problem here
    url: https://github.com/adiwajshing/Baileys/discussions/new
  - name: Discord
    about: Join our discord to discuss together
    url: https://discord.gg/WeJM5FP9GG
