name: Update WAProto

on:
  schedule:
  - cron: "10 1 * * 1"

jobs:
  update-proto:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: yarn --cwd proto-extract
    
    - name: Update WAProto.proto
      id: wa_proto_info
      run: |
        yarn --cwd proto-extract start > wa-logs.txt
        WA_VERSION=$(cat wa-logs.txt | perl -n -e'/Current version\: (.+)/ && print $1')
        WA_JS_URL=$(cat wa-logs.txt | perl -n -e'/Found source JS URL\: (.+)/ && print $1')
        echo "wa_version=$WA_VERSION" >> $GITHUB_OUTPUT
        echo "wa_js_url=$WA_JS_URL" >> $GITHUB_OUTPUT

    - name: GenerateStatics
      run: yarn --cwd proto-extract pbjs -t static-module -w commonjs -o ../WAProto/index.js ../WAProto/WAProto.proto   

    - name: GenerateStatics types
      run: yarn --cwd proto-extract pbts -o ../WAProto/index.d.ts ../WAProto/index.js   

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: 'chore: update proto'
          title: "Whatsapp v${{steps.wa_proto_info.outputs.wa_version}} change proto"
          branch: "update-proto/v${{steps.wa_proto_info.outputs.wa_version}}"
          branch-suffix: timestamp
          delete-branch: true
          labels: "update-proto"
          body: "Automated changes\nFound source JS URL: ${{steps.wa_proto_info.outputs.wa_js_url}}\nCurrent version: v${{steps.wa_proto_info.outputs.wa_version}}"
          add-paths: |
            WAProto/*