name: Update Docs

on:
  push:
    branches:
    - master
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.packageInfo.outputs.package-name }}
      package-version: ${{ steps.packageInfo.outputs.package-version }}
      commit-msg: ${{ steps.packageInfo.outputs.commit-msg }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v2

    - name: Parsing Package Info
      id: packageInfo
      run: |
        echo "::set-output name=package-name::$(jq -r .name package.json)"
        echo "::set-output name=package-version::$(jq -r .version package.json)"
        echo "::set-output name=commit-msg::$(git log -1 --pretty=%B)"
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn run build:all
      
    - name: Publish to Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages     
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}